apiVersion: argoproj.io/v1alpha1
kind: Experiment
metadata:
  name: experiment-with-analysis
spec:
  templates:
  - name: purple
    selector:
      matchLabels:
        app: rollouts-demo
    template:
      metadata:
        labels:
          app: rollouts-demo
      spec:
        containers:
        - name: rollouts-demo
          image: argoproj/rollouts-demo:purple
          imagePullPolicy: Always
  - name: orange
    selector:
      matchLabels:
        app: rollouts-demo
    template:
      metadata:
        labels:
          app: rollouts-demo
      spec:
        containers:
        - name: rollouts-demo
          image: argoproj/rollouts-demo:orange
          imagePullPolicy: Always
  analyses:
  - name: success-rate
    templateName: success-rate
