apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-four
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: istio-four
    repoURL: https://github.com/harikrongali/argo-combined-demo
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

