#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: wfwebhook
#data:
#  service.webhook.form: |
#    url: http://argo-server.argo.svc.cluster.local:2746/api/v1/events/argo/my-discriminator
#    headers:
#    - name: Content-Type
#      value: application/x-www-form-urlencoded
#    - name: Authorization
#      value: 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Im5OeTAzb0FsZE14UnFaX1VKYWtadExVS2c3ejBjZWkzWmlFVmtyRUdYSkkifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJhcmdvIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImplbmtpbnMtdG9rZW4tbjJraGsiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiamVua2lucyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjNiMDgzMzhmLWQwYjUtNGNiMS05OWMzLWFlYzU0Yjc4NGM3MyIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDphcmdvOmplbmtpbnMifQ.LqLwaOnDHBAgTY3qsgmNxWNU7YlNpnFJJPBIlCv-OnMcMFBcJLUhNYeg9OipglPWuY12GyXX7lHLktqrAo9lMrynF6DxaTR0T4485I3MQIw4BiFnJ3AV8ZFYL-JsbKq16E9UmBqZCLf0sv5HvkSCmUcVTGhDAqIReu10TtYBcPhdW-So6AZ75Q-sSP_grvc8oQ9Qi4Jma2cy0DLrIDAeCV2pKh7gmmNn2dU0K1rVGWLNfIJSGisFwM0_WKT6k3xZnNQ-0RtsLvgH_F-NIvHYm6K6f1qVtS4aLq-ZaGPIzmEiMojUzv_YuAMhFXrPNoG_nCVx1dNM-hYeDmLJq7HYQw'
#
#  template.form-data: |
#    webhook:
#      form:
#        method: POST
#        body: message=hello
#  curl $ARGO_SERVER/api/v1/workflows/argo/submit \
#  -fs \
#-H "Authorization: $ARGO_TOKEN" \
#-d '{"resourceKind": "WorkflowTemplate", "resourceName": "my-wf-tmple", "submitOptions": {"labels": "workflows.argoproj.io/workflow-template=my-wf-tmple"}}'

apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-rollouts-notification-configmap
  labels:
    app.kubernetes.io/instance: argo-rollouts
data:
  service.webhook.wfwebhook: |
    url: http://argo-server.argo.svc.cluster.local:2746/api/v1/events/argo/my-discriminator
    headers: #optional headers
    - name: Authorization
      value: 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Im5OeTAzb0FsZE14UnFaX1VKYWtadExVS2c3ejBjZWkzWmlFVmtyRUdYSkkifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJhcmdvIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImplbmtpbnMtdG9rZW4tbjJraGsiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiamVua2lucyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjNiMDgzMzhmLWQwYjUtNGNiMS05OWMzLWFlYzU0Yjc4NGM3MyIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDphcmdvOmplbmtpbnMifQ.LqLwaOnDHBAgTY3qsgmNxWNU7YlNpnFJJPBIlCv-OnMcMFBcJLUhNYeg9OipglPWuY12GyXX7lHLktqrAo9lMrynF6DxaTR0T4485I3MQIw4BiFnJ3AV8ZFYL-JsbKq16E9UmBqZCLf0sv5HvkSCmUcVTGhDAqIReu10TtYBcPhdW-So6AZ75Q-sSP_grvc8oQ9Qi4Jma2cy0DLrIDAeCV2pKh7gmmNn2dU0K1rVGWLNfIJSGisFwM0_WKT6k3xZnNQ-0RtsLvgH_F-NIvHYm6K6f1qVtS4aLq-ZaGPIzmEiMojUzv_YuAMhFXrPNoG_nCVx1dNM-hYeDmLJq7HYQw'
  template.rollout-completed: |
    webhook:
      wfwebhook:
        method: POST # one of: GET, POST, PUT, PATCH. Default value: GET
        body: |
          {"message": "hello"}
  template.rollout-step-completed: |
    webhook:
      wfwebhook:
        method: POST # one of: GET, POST, PUT, PATCH. Default value: GET
        body: |
          {"message": "hello"}
  trigger.on-rollout-completed: |
   - send: [rollout-completed]
  trigger.on-rollout-step-completed: |
    - send: [rollout-step-completed]
# notifications.argoproj.io/subscribe.on-rollout-complete.wfwebhook: ""