apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
    - name: initial-delay
      value: "10s"
    - name: count
      value: "10"
    - name: interval
      value: "10s"
    - name: failure-limit
      value: "1"
    - name: inconclusive-limit
      value: "1"
  metrics:
    - name: success-rate
      successCondition: result[0] > 58
      initialDelay: "{{args.initial-delay}}"
      interval: "{{args.interval}}"
      count: "{{args.count}}"
      failureLimit: "{{args.failure-limit}}"
      inconclusiveLimit: "{{args.inconclusive-limit}}"
      provider:
        prometheus:
          address: "http://prometheus.istio-system.svc.cluster.local:9090"
          query: |-
             (sum(sum_over_time(istio_requests_total{response_code=~"2[0-9]+", namespace="default"}[11m]))/sum(sum_over_time(istio_requests_total{namespace="default"}[11m]))) * 100
